question_data = [
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
                  "correct_answer": "True" or "T",  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "Vietnam is the only country in the world that starts with V. ",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "&quot;Return to Castle Wolfenstein&quot; was the only game of the Wolfenstein series where you don&#039;t play as William &quot;B.J.&quot; Blazkowicz.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Minecraft wasn&rsquo;t the original name to Minecraft.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Pistons were added to Minecraft in Beta 1.5.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Computers",
                  "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Japanese Anime &amp; Manga",
                  "question": "In Full Metal Panic!, Whispered are those who are capable of creating Black Technology.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Mythology",
                  "question": "According to Norse mythology, Loki is a mother.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "Ferrari has never made a V10 engine for any of its cars.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Music",
                  "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "You are allowed to sell your soul on eBay.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "The Olympics tennis court is a giant green screen.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "Kissing someone for one minute burns about 2 calories.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Cartoon &amp; Animations",
                  "question": "Nutcracker Suite was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "&quot;Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.&quot; is a grammatically correct sentence.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "Oxford University is older than the Aztec Empire. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "Antarctica is the largest desert in the world.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "The Korean War ended in 1953 without any ceasefire.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "Nintendo started out as a playing card manufacturer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; takes place on Shadow Moses Island.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Animals",
                  "question": "The average lifespan of a wildcat is only around 5-6 years. ",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Mathematics",
                  "question": "A &#039;Millinillion&#039; is a real number.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Computers",
                  "question": "The first computer bug was formed by faulty wires.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Board Games",
                  "question": "In the game &quot;Racko&quot; you may pick up ANY card from the discard pile.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Television",
                  "question": "Klingons respect their disabled comrades, and those who are old, injuried, and helpless.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "The Japanese Shinkansen beat the French TGV&#039;s speed record for fastest electric rail train.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Computers",
                  "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Mythology",
                  "question": "In Greek mythology, Hera is the goddess of harvest.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Music",
                  "question": "&quot;Neutral Milk Hotel&quot; is a real band.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "There are 86400 seconds in a day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Japanese Anime &amp; Manga",
                  "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Music",
                  "question": "Nick Mason is the only member to appear on every Pink Floyd album.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science &amp; Nature",
                  "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "Japan has left-hand side traffic.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Video Games",
                  "question": "In Riot Games &quot;League of Legends&quot; the name of Halloween event is called &quot;The Reckoning&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Mythology",
                  "question": "The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Music",
                  "question": "Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "The French word to travel is &quot;Travail&quot;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science &amp; Nature",
                  "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                  "question": "The majority of Subaru vehicles are made in China.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Computers",
                  "question": "All program codes have to be compiled into an executable file in order to be run. "
                              "This file can then be executed on any machine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Film",
                  "question": "There aren&#039;t any live-action clones in &quot;Star Wars: Episode III - Revenge of the Sith&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Mathematics",
                  "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
